fn() {
  try {
    alert(1)
  } catch e {
    throw e
  }
}
